<a href="https://colab.research.google.com/github/carlosramos1/numpy-pandas-matplotlib/blob/main/PD05_lectura_y_escritura_de_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extracción y almacenamiento de dataframes y series.

In [24]:
import pandas as pd
import numpy as np

pd.__version__, np.__version__

('2.2.2', '2.0.2')

Una de las fortalezas de Pandas es su capacidad de extraer información de diversas fuentes de datos.

## Extraer un csv desde una URL

In [25]:
url = 'https://raw.githubusercontent.com/carlosramos1/datasets/refs/heads/main/reviews_filmaffinity.csv'
reviews_df = pd.read_csv(url, delimiter=r'\|\|', header=0, engine='python')
reviews_df.sample(5)

,film_name,gender,film_avg_rate,review_rate,review_title,review_text
1120,El orfanato,Terror,"6,7",7.0,Que no quede huérfana,Hacía mucho que una película de miedo no me po...
442,Ocho apellidos vascos,Comedia,"6,0",9.0,Una película con más de sola una historia de u...,Esta película hace un buen trabajo en mostrand...
7141,Los crímenes de Oxford,Intriga,"5,7",4.0,¿Se ha perdido en Oxford?,"¿Se ha perdido en Oxford, Álex de la Iglesia? ..."
3953,Celda 211,Thriller,"7,7",8.0,Historia sin concesiones sobre la violencia y ...,Auténtica. Honesta. Seca. Potente. Nunca pierd...
55,Ocho apellidos vascos,Comedia,"6,0",7.0,Tópicos,Película de tópicos. Cuando digo tópicos no es...

## Funciones de lectura de Pandas.

* ```pd.read_clipboard()``` Permite leer datos que se encuentran en el espacio de memoria del "clipboard" en un sistemas.
* ```pd.read_csv()``` Permite leer datos que se encuentran en un archivo *CSV*.
* ```pd.read_excel()```  Permite leer datos que se encuentran en un archivo de *Excel*.
* ```pd.read_feather()``` Permite leer datos a partir de [*feather*](https://github.com/wesm/feather).
* ```pd.read_fwf()```.
* ```pd.read_gbq()``` para [*Google Big Query*](https://pandas-gbq.readthedocs.io/en/latest/).
* ```pd.read_hdf()``` para [HDF5](https://www.hdfgroup.org/solutions/hdf5).
* ```pd.read_html()``` https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_html.html.
* ```pd.read_json()```.
* ```pd.read_msgpack()``` https://pandas-msgpack.readthedocs.io/en/latest/.
* ```pd.read_parquet()```.
* ```pd.read_pickle()```.
* ```pd.read_sas()```.
* ```pd. read_sql()```.
* ```pd.read_sql_query()```.
* ```pd.read_sql_table()```.
* ```pd.read_stata()```.
* ```pd.read_table()```.

## Métodos de persistencia y almacenamiento de los dataframes de *Pandas*.

* ```pd.DataFrame.to_clipboard()```
* ```pd.DataFrame.to_csv()```
* ```pd.DataFrame.to_dict()```
* ```pd.DataFrame.to_excel()```
* ```pd.DataFrame.to_feather()```
* ```pd.DataFrame.to_gbq()```
* ```pd.DataFrame.to_hdf()```
* ```pd.DataFrame.to_html```
* ```pd.DataFrame.to_json()```
* ```pd.DataFrame.to_latex()```
* ```pd.DataFrame.to_msgpack()```
* ```pd.DataFrame.to_numpy()```
* ```pd.DataFrame.to_parquet()```
* ```pd.DataFrame.to_pickle()```
* ```pd.DataFrame.to_records()```
* ```pd.DataFrame.to_sql()```
* ```pd.DataFrame.to_stata()```

## Lectura de una hoja de cálculo.

In [26]:
import urllib.request

In [27]:
url_data = 'https://github.com/carlosramos1/datasets/raw/refs/heads/main/datos_toy.xlsx'
urllib.request.urlretrieve(url_data, "datos.xlsx")

('datos.xlsx', <http.client.HTTPMessage at 0x7e6dcda21880>)

In [28]:
%ls *.xlsx

datos.xlsx

In [29]:
excel = pd.read_excel('datos.xlsx', engine='openpyxl')

In [30]:
excel

     NOMBRE  EDAD       PAIS
0  Fernando    24    BOLIVIA
1      Luis    23  ARGENTINA
2     Oscar    35    BOLIVIA
3     Maria    27       PERU
4   Daniela    30       PERU